//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVWA.Models.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int book_id { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
        public int author_id { get; set; }
    }
}
